version: '3.4'

services:

  technical.test.mssql:
    container_name: technicaltest_mssql_development
    image: technicaltest/database/mssql:development
    build:
      context: ./database
      dockerfile: Dockerfile
    networks:
      - technicaltest-net
    restart: always


  technical.test.gateway.api.development:
    container_name: technicaltest_gateway_api_development
    image: technicaltest/gateway/api:development
    build:
      context: ./backend/Service.Gateway.Api
      dockerfile: Dockerfile
    networks:
      - technicaltest-net
    restart: always

  technical.test.security.api.development:
    container_name: technicaltest_security_api_development
    image: technicaltest/security/api:development
    build:
      context: ./backend/Service.Security.Api
      dockerfile: Dockerfile
    networks:
      - technicaltest-net
    restart: always
  
  technical.test.categories.api.development:
    container_name: technicaltest_categories_api_development
    image: technicaltest/categories/api:development
    build:
      context: ./backend/Service.Categories.Api
      dockerfile: Dockerfile
    networks:
      - technicaltest-net
    restart: always

  technical.test.angular.frontend.development:
    container_name: technicaltest_angular_frontend_development
    image: technicaltest/angular/frontend:development
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: development
    networks:
      - technicaltest-net
    restart: always

networks:
  technicaltest-net:
    driver: bridge