version: '3.4'

services:
  technical.test.gateway.api.development:
    image: technicaltest/gateway/api:development
    build:
      context: .
      dockerfile: backend/Service.Gateway.Api/Dockerfile
    container_name: technicaltest_gateway_api_development
    networks:
      technicaltest-net:
        aliases: 
          - technicaltest-net
    restart: unless-stopped

  technical.test.security.api.development:
    image: technicaltest/security/api:development
    build:
      context: .
      dockerfile: backend/Service.Security.Api/Dockerfile
    container_name: technicaltest_security_api_development
    networks:
      technicaltest-net:
        aliases: 
          - technicaltest-net
    restart: unless-stopped
  
  technical.test.categories.api.development:
    image: technicaltest/categories/api:development
    build:
      context: .
      dockerfile: backend/Service.Categories.Api/Dockerfile
    container_name: technicaltest_categories_api_development
    networks:
      technicaltest-net:
        aliases: 
          - technicaltest-net
    restart: unless-stopped

# volumes:
  # data-development:
  # data-production:

networks:
  technicaltest-net: