version: '3.4'

services:
  technical.test.mssql:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Jerios@091311
    ports:
      - "1433:1433"

  technical.test.gateway.api.development:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8501:80"

  technical.test.security.api.development:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__Database="Data Source=c490dee37662;Initial Catalog=Security;User Id=sa;Password=Jerios@091311;"
      - ConnectionStrings__Database=Server=technicaltest_mssql_development;Database=Security;User=sa;Password=Jerios@091311
    ports:
      - "8502:80"

  technical.test.categories.api.development:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__Database="Data Source=c490dee37662;Initial Catalog=Categories;User Id=sa;Password=Jerios@091311;"
      - ConnectionStrings__Database=Server=technicaltest_mssql_development;Database=Categories;User=sa;Password=Jerios@091311
    ports:
      - "8503:80"

  technical.test.angular.frontend.development:
    ports:
      - "8500:80"
